### PR TITLE
allow missing msg.namespace

### PR DESCRIPTION
**Pull request by colwilson**
as per #1

### CODE REVIEW

**Comment by nathantsoi** [comment]
sry, i always for get to hit "finish review" @colwilson. im excited to merge this, just not sure about the 2 comments above.

**Comment by mmacneil** [comment]
Hey @nathantsoi - great lib btw.  Any closer to merging this fix?  I hit the same snag @colwilson resolved in this pr and would be great if it was repaired.  I believe your questions/confirmations are correct - he's using the new concat() function which properly accomodates for messages missing `namespace` when building the action path.

thanks
Mark

**Comment by nathantsoi** [comment]
sweet, thx @mmacneil, i was actually just working on bringing up tests and covering this, should be done shortly and i'll get this merged in.

**Comment by mmacneil** [comment]
Awesome, thanks man

**Comment by nathantsoi** [comment]
done in https://github.com/nathantsoi/vue-native-websocket/pull/6

**Pull request closed without merging**
